const status = document.getElementById("status");
const fill = document.getElementById("fill");
const fillProfile = document.getElementById("fillProfile");
const manageProfile = document.getElementById("manageProfile");
const fillOtp = document.getElementById("fillOtp");
const clear = document.getElementById("clear");
const APPROVED_ROOTS = ["uidai.gov.in", "gst.gov.in", "udyamregistration.gov.in", "eci.gov.in", "nsdl.com", "utiitsl.com", "fssai.gov.in", "parivahan.gov.in", "passportindia.gov.in", "incometax.gov.in", "mca.gov.in", "epfindia.gov.in", "eshram.gov.in", "gem.gov.in", "startupindia.gov.in", "icegate.gov.in", "dgft.gov.in", "crsorgi.gov.in", "india.gov.in"];
const isApprovedPortal = url => { try { const host = new URL(url).hostname.toLowerCase().replace(/^www\./, ""); return url.startsWith("https://") && APPROVED_ROOTS.some(root => host === root || host.endsWith(`.${root}`)); } catch { return false; } };
function renderSavedStatus() { chrome.storage.local.get(["preparedForm", "personalProfile"], ({ preparedForm, personalProfile }) => { const app = preparedForm?.form ? `${preparedForm.serviceTitle || preparedForm.serviceId || "Application"}: ${Object.keys(preparedForm.form).length} fields` : "No prepared application"; const count = personalProfile && typeof personalProfile === "object" ? Object.keys(personalProfile).filter(k => String(personalProfile[k] ?? "").trim()).length : 0; status.textContent = `${app} · Personal profile: ${count} fields saved`; }); }
renderSavedStatus();
async function sendFillMessage(type) { status.textContent = "Checking current page…"; const [tab] = await chrome.tabs.query({ active: true, lastFocusedWindow: true }); if (!tab?.id || !isApprovedPortal(tab.url || "")) { status.textContent = "This page isn't in the approved portal list. Open a supported official HTTPS portal and retry."; return; } try { const result = await chrome.tabs.sendMessage(tab.id, { type }); status.textContent = result?.ok ? `Filled ${result.filled} matching fields. ${result.notMatched?.length ? `Unmatched: ${result.notMatched.join(", ")}. ` : ""}${result.message}` : (result?.message || "Could not fill this page. Reload it and try again."); } catch { status.textContent = "No form assistant detected. Confirm the portal is supported, then reload the portal after updating the extension."; } }
fill.addEventListener("click", () => sendFillMessage("NB_FILL_ACTIVE_PORTAL"));
fillProfile.addEventListener("click", () => sendFillMessage("NB_FILL_PERSONAL_PROFILE"));
fillOtp.addEventListener("click", () => sendFillMessage("NB_FILL_AND_REQUEST_OTP"));
manageProfile.addEventListener("click", () => chrome.runtime.openOptionsPage());
clear.addEventListener("click", async () => { const { preparedForm } = await chrome.storage.local.get(["preparedForm"]); if (!preparedForm?.form) { status.textContent = "No saved application to delete."; return; } const registration = preparedForm.serviceTitle || preparedForm.serviceId || "saved application"; if (!confirm(`Delete ${registration} from this browser? This cannot be undone.`)) { status.textContent = "Deletion cancelled."; return; } await chrome.storage.local.remove("preparedForm"); status.textContent = "Saved application deleted from this browser."; });
chrome.storage.onChanged.addListener((changes, area) => { if (area === "local" && (changes.preparedForm || changes.personalProfile)) renderSavedStatus(); });