const status = document.getElementById("status");
const fill = document.getElementById("fill");
const fillOtp = document.getElementById("fillOtp");
const clear = document.getElementById("clear");
const APPROVED_ROOTS = ["uidai.gov.in", "gst.gov.in", "udyamregistration.gov.in", "eci.gov.in", "nsdl.com", "utiitsl.com", "fssai.gov.in", "parivahan.gov.in", "passportindia.gov.in", "incometax.gov.in", "mca.gov.in", "epfindia.gov.in", "eshram.gov.in", "gem.gov.in", "startupindia.gov.in", "icegate.gov.in", "dgft.gov.in", "crsorgi.gov.in", "india.gov.in"];
const isApprovedPortal = url => { try { const host = new URL(url).hostname.toLowerCase().replace(/^www\./, ""); return url.startsWith("https://") && APPROVED_ROOTS.some(root => host === root || host.endsWith(`.${root}`)); } catch { return false; } };
function renderSavedStatus() { chrome.storage.local.get(["preparedForm"], ({ preparedForm }) => { if (preparedForm?.form) { const savedAt = preparedForm.preparedAt ? new Date(preparedForm.preparedAt).toLocaleString() : "unknown time"; status.textContent = `Saved: ${preparedForm.serviceTitle || preparedForm.serviceId || "Registration"} · ${Object.keys(preparedForm.form).length} fields · ${savedAt}`; } else status.textContent = "No saved application. Open a Namaskar Bharat application, prepare its details, and send them to Form Assistant."; }); }
renderSavedStatus();
async function sendFillMessage(type) { status.textContent = "Checking current page…"; const [tab] = await chrome.tabs.query({ active: true, lastFocusedWindow: true }); if (!tab?.id || !isApprovedPortal(tab.url || "")) { status.textContent = "This page isn't in the extension's approved portal list. Open a supported official portal and retry."; return; } try { const result = await chrome.tabs.sendMessage(tab.id, { type }); status.textContent = result?.ok ? `Filled ${result.filled} matching fields. ${result.notMatched?.length ? `Unmatched: ${result.notMatched.join(", ")}. ` : ""}${result.message}` : (result?.message || "Could not fill this page. Reload it and try again."); } catch { status.textContent = "No form assistant detected. Confirm the site is approved, then reload the portal after updating the extension."; } }
fill.addEventListener("click", () => sendFillMessage("NB_FILL_ACTIVE_PORTAL")); fillOtp.addEventListener("click", () => sendFillMessage("NB_FILL_AND_REQUEST_OTP"));
clear.addEventListener("click", async () => { const { preparedForm } = await chrome.storage.local.get(["preparedForm"]); if (!preparedForm?.form) { status.textContent = "No saved application to delete."; return; } const registration = preparedForm.serviceTitle || preparedForm.serviceId || "saved application"; if (!confirm(`Delete ${registration} from this browser? This cannot be undone.`)) { status.textContent = "Deletion cancelled."; return; } await chrome.storage.local.remove("preparedForm"); status.textContent = "Saved application deleted from this browser."; });
chrome.storage.onChanged.addListener((changes, area) => { if (area === "local" && changes.preparedForm) renderSavedStatus(); });
